server:
  ssl:
    key-store: classpath:senagi.site.p12
    key-store-password: ssafy
    key-store-type: PKCS12
    key-alias: ssafy

spring:
  profiles:
    include: eth

  datasource:
    url: jdbc:mysql://senagi.site:17177/nobaddonation?useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: ssafy
    password: ssafyb105
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
              client-id: 1016569789271-jgg8dcis0dvb9avb4n7jfo5nv43p4897.apps.googleusercontent.com
              client-secret: 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
              scope:
              - email
              - profile
  data:
    web:
      pageable:
        #페이지 기본 사이즈
        default-page-size: 12

  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

jwt:
  token:
    header: Authorization
    issuer: NoBadDonation
    secret: 41NTQUZZLTYtRGVhamVvbi0xLUIxMDUtaGVyZS1Jcy1Oby1CYWQtRG9uYXRpb24K # "SSAFY-6-Deajeon-1-B105-There-Is-No-Bad-Donation" Base64 Encoding 대문자 8, 소문자 4
    expirySeconds: 86400

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

uploadPath:
  path: "./imgs/"

